#!/usr/bin/env bun
/**
 * Render the GitHub Release body for a `zac submit` that just landed on
 * `main`. The release is tagged with the merge commit SHA; this body
 * tells signers what was proposed and gives them per-Safe deep links.
 *
 * Inputs (positional):
 *   1. plan-diff.txt   — captured stdout from `zac plan`
 *      (human-readable `printPlanDiff` output, one `plan:` block per
 *      safe-dir).
 *   2. submit-log.txt  — captured stdout from `zac submit`
 *      (one `submitted safe=… chain=… (N plans): safeTxHash 0x…` line
 *      per posted proposal). Included verbatim as proof the propose
 *      step succeeded.
 *   3. config-root     — root dir to walk for `*.plan.json`.
 *
 * Env (optional, used in framing):
 *   - COMMIT_SHA       — `github.sha` of the merge commit. Falls back
 *     to `0000000` when not set (local script runs).
 *   - COMMIT_MESSAGE   — `github.event.head_commit.message`. Used to
 *     surface the PR title and number in the release body header.
 *
 * Writes markdown to stdout; the workflow redirects to `release-body.md`
 * and passes that to `softprops/action-gh-release` as `body_path`.
 *
 * Multi-chain / multi-safe in one push is first-class: every
 * `(chainId, safeAddress)` group becomes its own detail block.
 */

import { readFileSync } from 'node:fs';
import {
  chainLabel,
  parseSubmitLog,
  safeAppLink,
  shortAddr,
  sortPlans,
  type SubmitRecord,
} from './_shared';

const OPERATION_LABEL: Record<number, string> = {
  0: '0 (CALL)',
  1: '1 (DELEGATECALL)',
};

function renderHeader(commitSha: string, commitMessage: string, safes: number, chains: number): string {
  const firstLine = commitMessage.split('\n')[0] ?? '';
  const lines = [
    '## 🚀 Safe role updates',
    '',
    `This release records the Safe transactions proposed when commit \`${commitSha.slice(0, 7)}\` landed on \`main\`.`,
    '',
    `**${safes} safe${safes === 1 ? '' : 's'} across ${chains} chain${chains === 1 ? '' : 's'}** were proposed via \`zac submit\`. Each proposal is now waiting in Safe Transaction Service for owners to co-sign and execute.`,
  ];
  if (firstLine !== '') {
    lines.push('', `> Triggered by: ${firstLine}`);
  }
  return lines.join('\n');
}

function renderSummaryTable(plans: SubmitRecord[]): string {
  const rows = plans
    .map((p) => {
      const link = safeAppLink(p.chainId, p.safeAddress, p.safeTxHash);
      const hashCell =
        link === '' ? `\`${p.safeTxHash}\`` : `[\`${p.safeTxHash.slice(0, 10)}…\`](${link})`;
      return `| \`${shortAddr(p.safeAddress)}\` | ${chainLabel(p.chainId)} | ${p.callsCount} | ${p.nonce} | ${hashCell} |`;
    })
    .join('\n');
  return [
    '### Summary',
    '',
    '| Safe | Chain | Calls | Nonce | safeTxHash |',
    '|------|-------|-------|-------|------------|',
    rows,
    '',
  ].join('\n');
}

function renderPerSafeDetails(plans: SubmitRecord[]): string {
  const blocks = plans.map((p) => {
    const opLabel = OPERATION_LABEL[p.operation] ?? `${p.operation}`;
    const link = safeAppLink(p.chainId, p.safeAddress, p.safeTxHash);
    const lines = [
      `#### \`${p.safeAddress}\` @ ${chainLabel(p.chainId)}`,
      '',
      `- **safeTxHash**:  \`${p.safeTxHash}\``,
      `- **messageHash**: \`${p.messageHash}\``,
    ];
    if (p.domainHash !== undefined && p.domainHash !== '') {
      lines.push(`- **domainHash**:  \`${p.domainHash}\``);
    }
    lines.push(
      `- **Nonce**: ${p.nonce}`,
      `- **Operation**: ${opLabel}`,
      `- **Calls**: ${p.callsCount}`,
    );
    if (link !== '') {
      lines.push(`- **Sign in Safe app**: ${link}`);
    }
    if (p.nestedSigners.length > 0) {
      lines.push(
        '',
        `- **Nested signers** — owner(s) of this Safe that are themselves Safes. Each approves by executing \`approveHash(safeTxHash)\`, so its own signers sign the **child transaction** below (computed at the shown child nonce). On a Ledger, verify the **Domain hash** and **Message hash**; \`safeTxHash\` is the child tx's final digest.`,
      );
      for (const n of p.nestedSigners) {
        lines.push(
          `  - \`${n.child}\` (child nonce ${n.nonce})`,
          `    - Domain hash:  \`${n.domainHash}\``,
          `    - Message hash: \`${n.messageHash}\``,
          `    - safeTxHash:   \`${n.safeTxHash}\``,
        );
      }
    }
    return lines.join('\n');
  });
  return ['### Per-Safe details', ...blocks].join('\n\n');
}

function renderDiff(diff: string): string {
  const trimmed = diff.trim();
  if (trimmed === '') return '';
  return ['### Plan diff', '', '```', trimmed, '```', ''].join('\n');
}

function renderSubmitLog(log: string): string {
  const trimmed = log.trim();
  if (trimmed === '') return '';
  return ['### Submit log', '', '```', trimmed, '```', ''].join('\n');
}

function renderFooter(commitSha: string): string {
  return [
    '---',
    `Generated by \`.github/workflows/release.yml\` for commit \`${commitSha}\`.`,
    '',
    'Plan JSON artifacts for each safe are attached below — the role-update calldata bundled into each proposed Safe transaction.',
  ].join('\n');
}

function main(): void {
  const [diffPath, submitLogPath] = process.argv.slice(2);
  if (diffPath === undefined || submitLogPath === undefined) {
    process.stderr.write(
      'usage: build-release-body.ts <plan-diff.txt> <submit-log.txt> [config-root]\n',
    );
    process.exit(2);
  }
  const commitSha = process.env['COMMIT_SHA'] ?? '0000000';
  const commitMessage = process.env['COMMIT_MESSAGE'] ?? '';
  const diff = readFileSync(diffPath, 'utf8');
  const submitLog = readFileSync(submitLogPath, 'utf8');
  // Per-Safe signing data (safeTxHash / messageHash / nonce / operation) is
  // built against the live Safe at submit time, so it comes from the submit
  // log, not the plan JSON.
  const plans = sortPlans(parseSubmitLog(submitLog));
  if (plans.length === 0) {
    // Defensive: the workflow gates this step on `has_changes == true`,
    // so this path should never run in CI. Local script invocations
    // still get a readable error.
    process.stderr.write(
      'build-release-body.ts: no `submitted safe=…` lines in submit log — refusing to render an empty release body\n',
    );
    process.exit(1);
  }
  const chains = new Set(plans.map((p) => p.chainId)).size;
  const safes = new Set(plans.map((p) => `${p.chainId}:${p.safeAddress.toLowerCase()}`)).size;

  const sections = [
    renderHeader(commitSha, commitMessage, safes, chains),
    renderSummaryTable(plans),
    renderPerSafeDetails(plans),
    renderDiff(diff),
    renderSubmitLog(submitLog),
    renderFooter(commitSha),
  ].filter((s) => s !== '');

  process.stdout.write(sections.join('\n\n') + '\n');
}

main();
