roles_modifier_address: "{{ aliases.modifiers.cs_diversified_strategy_treasury_wallet_modifier }}"
safe_address: "{{ aliases.safes.cs_diversified_strategy_treasury_wallet_safe }}"
chain_id: 1
name: Ondo OUSG USDC Manager
description: Subscribe and redeem OUSG with USDC on Mainnet
configs:
  - template: "../../../zac/templates/ondo_ousg/ondo_ousg.tmpl"
    key: ONDO_OUSG
    members:
      - "{{ aliases.signers.cs_execution_quorum }}"
    params:
      payment_assets:
        - "USDC"
