roles_modifier_address: "{{ aliases.modifiers.cs_diversified_strategy_treasury_wallet_modifier }}"
safe_address: "{{ aliases.safes.cs_diversified_strategy_treasury_wallet_safe }}"
chain_id: 1
name: Ondo Global Markets Manager
description: Mint and redeem Ondo GM tokens (HYGon, TLTon, SHYon, IEFon) with USDC on Mainnet
configs:
  - template: "../../../zac/templates/ondo_gm/ondo_gm.tmpl"
    key: ONDO_GM
    members:
      - "{{ aliases.signers.cs_execution_quorum }}"
    params:
      gm_tokens:
        - "HYGon"
        - "TLTon"
        - "SHYon"
        - "IEFon"
        - "SGOVon"
      payment_assets:
        - "USDC"
