roles_modifier_address: "{{ aliases.modifiers.poc_test_cs_modifier }}"
safe_address: "{{ aliases.safes.poc_test_cs_treasury_wallet_id_diversified_income }}"
chain_id: 1
name: Compound V3 USDC Manager
description: Supply and withdraw USDC on Compound V3 Mainnet
configs:
  - template: "../../../zac/templates/compound_v3/compound_v3.tmpl"
    key: COMPOUND_V3
    members:
      - "{{ aliases.signers.poc_test_cs_execution_manager }}"
    params:
      deposit_assets:
        - "USDC"
