roles_modifier_address: "{{ aliases.modifiers.poc_test_cs_modifier }}"
safe_address: "{{ aliases.safes.poc_test_cs_treasury_wallet_id_diversified_income }}"
chain_id: 1
name: Morpho Blue USDC Manager
description: Supply and withdraw USDC across selected Morpho Blue markets on Mainnet
configs:
  - template: "../../../zac/templates/morpho_blue/morpho_blue.tmpl"
    key: MORPHO_BLUE
    members:
      - "{{ aliases.signers.poc_test_cs_execution_manager }}"
    params:
      markets:
        - "usdc_cbbtc_86"
        - "usdc_wbtc_86"
        - "usdc_pteth_915"
        - "usdc_wsteth_86"
        - "usdc_resteth_915"
