roles_modifier_address: "{{ aliases.modifiers.poc_test_cs_modifier }}"
safe_address: "{{ aliases.safes.poc_test_cs_treasury_wallet_id_diversified_income }}"
chain_id: 1
name: Ondo Global Markets Manager
description: Mint and redeem Ondo GM tokens (HYGon, TLTon, SHYon, IEFon) with USDC on Mainnet
configs:
  - template: "../../../zac/templates/ondo_gm/ondo_gm.tmpl"
    key: ONDO_GM
    members:
      - "{{ aliases.signers.poc_test_cs_execution_manager }}"
    params:
      gm_tokens:
        - "HYGon"
        - "TLTon"
        - "SHYon"
        - "IEFon"
        - "SGOVon"
      payment_assets:
        - "USDC"
