roles_modifier_address: "{{ aliases.modifiers.modifier }}"
safe_address: "{{ aliases.safes.test_safe }}"
chain_id: 11155111
name: Ethena USDe Manager
description: Mint/redeem USDe (USDC, USDT collateral) and stake/unstake sUSDe on Ethena Mainnet
configs:
  - template: "../../../zac/templates/ethena/ethena.tmpl"
    key: ETHENA
    members:
      - "{{ aliases.signers.test_signer }}"
    params:
      operator: "{{ aliases.signers.test_signer }}"
      collateral_assets:
        - "USDC"
